### ISSUE TITLE
How to grab value of placeholder without needing player present?

### ISSUE THREAD

**Issue by xYosemite** [APickledWalrus/skript-placeholders#19] opened 2021-01-17 04:24 UTC
1.5.1, latest.
### Description

I am trying to implement a way to grab the current capper from a King Of The Hill plugin as I want to give them damage resistance. However, I'm not sure how to make it so the variable {capper} is set to that variable without a player having to be online? I want it to just grab the value of the placeholder and value it in a variable in the script.

Example:
`every 1 second in world "world": #this is done as there is no skript even for the koth plugin
	set {capper} to the placeholder "koth_currentcapper":  # trying to set the capper placeholder to the value`

This doesn't work as it's not proper syntax, a player is required.

However, this obviously works:
`command /capper:
	trigger:
		set {_capper} to placeholder "koth_currentcapper" from player
		message "%{_capper}%"`

Is there any way the server can just grab the value of a global variable at any moment without a player needing to be present? Is there any work-arounds? "koth_currentcapper" is from Subside's KoTH plugin and is global, meaning that it's no different for certain players.

**Comment by APickledWalrus** [comment] 2021-01-17 04:38
`placeholder %string%` should work I think... what if you do `parse placeholder %string%`

**Comment by xYosemite** [comment] 2021-01-17 04:55
Says cannot understand this condition.

How do you mean exactly? I have tried `set {_capper} to placeholder "koth_currentcapper" from player` and `parse placeholder "koth_currentcapper" as {capper}`

Do you have an example?

**Comment by APickledWalrus** [comment] 2021-01-17 04:57
Try 

`set {variable} to parse placeholder "PLACEHOLDER NAME"`

to do it without needing a player
player argument is supposed to be optional

**Comment by xYosemite** [comment] 2021-01-17 17:25
I tried this originally, does not work.

Are you sure it is optional?

**Comment by APickledWalrus** [comment] 2021-01-17 17:27
It is supposed to be. I will take a look at this when I can :)

**Comment by xYosemite** [comment] 2021-01-17 17:33
Thanks, man. I hope you can try sort it out ASAP- I want to be able to use this for my KoTH gamemode. :)

**Comment by APickledWalrus** [comment] 2021-02-06 18:37
Sorry for not giving you an update. I had no issues getting a result without a player present. Here is the code I used:
```
command /test:
	trigger:
		set {_p} to parse placeholder "server_tps"
		send "RESULT: '%{_p}%'" to executor
```

It successfully prints the following: `RESULT: '*20.0, *20.0, *20.0, '` 
(This was ran both in game and from console)

PlaceholderAPI 2.10.9
skript-placeholders 1.5.1

**Comment by oskarkk** [comment] 2021-03-23 01:35
Hi, maybe I should make a new issue, but among other problems, for me the plugin is particularly broken in your example. On a test server I cannot get it to parse `%server_tps%` with or without player I'm getting only `<none>`. Placeholders `%server_online%` and `%player_level%` work.

But on my main server, only `%server_online%` works (with or without player specified). `%player_level%`, `%server_tps%` and `%essentials_safe_online%` are giving none (with or without player specified), while the TAB plugin gets all of them without problems.

Test server runs Paper-556 (MC: 1.16.5), Skript Version: 2.5.3, skript-placeholders v1.5.1 and PlaceholderAPI (2.10.9). Main server runs on Paper-552, the rest is the same.

**Comment by APickledWalrus** [comment] 2021-03-26 17:16
All placeholder values are returned as Strings, so I am not sure why you might be having that issue. However, if you got it working okay on your end it should be good. I am going to close this issue because I am still unable to reproduce it. If either of you are still having issues, feel free to comment here (even though it's closed).

**Closed by APickledWalrus** 2021-03-26 17:16 UTC
Labels: question, waiting for response
