### ISSUE TITLE
Reloading skript breaks other placeholders

### ISSUE THREAD

**Issue by RealSypher** [APickledWalrus/skript-placeholders#59] opened 2024-06-18 04:33 UTC
### Description
Whenever I reload a skript, another skript's placeholders break.

### Steps to Reproduce
Reload a skript with a placeholder, then reload another skript with a placeholder.

### Expected Behavior
All placeholders work

### Errors / Screenshots

https://youtu.be/xKPziHIg3Sw

![image](https://github.com/APickledWalrus/skript-placeholders/assets/69989573/64cffb15-6a2d-4fb0-b8f9-3878bbf9a05f)

### Server Information
* **Server version/platform:**   1.19.4
* **skript-placeholders version:**   1.6.0 
* **Skript version:**    2.8.6
* **PlaceholderAPI version (if applicable):**   2.11.6
* **MVdWPlaceholderAPI version (if applicable):**    N/A

**Comment by APickledWalrus** [comment] 2024-06-18 05:19
Are you registering a placeholder with the same prefix in multiple scripts?

**Comment by RealSypher** [comment] 2024-06-18 05:53
Yes. However, I did this a while ago in 1.18 and it worked fine.

**Comment by RealSypher** [comment] 2024-06-18 05:54
To add, I am reusing the exact same skripts and after reviewing the documentation they should still work fine....

**Comment by APickledWalrus** [comment] 2024-06-18 05:58
Ah yeah I can see why it stopped working. I believe I fixed this issue already in the upcoming 1.7.0 release. I'll try to see if I can get that out this week.

**Comment by RealSypher** [comment] 2024-06-18 06:07
Alright, thanks! Looking forward to it.

**Comment by APickledWalrus** [comment] 2024-06-18 06:14
I'll keep this open for now until I confirm the issue is resolved and until 1.7.0 is released. 🙂

**Comment by RealSypher** [comment] 2024-06-27 03:02
Is there an ETA for the update?

**Comment by APickledWalrus** [comment] 2024-06-27 17:33
Sorry, I'm aiming to get it out by the end of the week (Friday/Saturday)

**Comment by RealSypher** [comment] 2024-06-27 19:39
No worries, take your time!

**Comment by APickledWalrus** [comment] 2024-08-20 20:37
This should be fixed in the latest release. Thank you very much for your patience!

**Closed** 2024-08-20 20:37 UTC
Labels: bug, completed
