### ISSUE TITLE
Can't compare?

### ISSUE THREAD

**Issue by zimzaza4** [APickledWalrus/skript-placeholders#20] opened 2021-01-28 07:01 UTC
### Description

Can't compare
### Steps to Reproduce

on placeholderapi placeholder request for the prefix "custom":
  if the identifier is "message": 
    set the result to "Hey there %player%!"
### Expected Behavior

The code should execute correctly
### Errors / Screenshots

![IMG20210128145741](https://user-images.githubusercontent.com/53421735/106101697-3569df00-6179-11eb-8f47-ed35cb942d14.jpg)

### Server Information
* **Server version/platform:**       
![IMG20210128150250](https://user-images.githubusercontent.com/53421735/106102147-ea040080-6179-11eb-84a1-11626b35f4a0.jpg)

* **skript-placeholders version:**                
* **Skript version:**                
* 
![IMG20210128150423](https://user-images.githubusercontent.com/53421735/106102317-2b94ab80-617a-11eb-957d-c35879f554ed.jpg)

* **PlaceholderAPI version (if applicable):**                
* 2.10.9
* **MVdWPlaceholderAPI version (if applicable):**

**Comment by APickledWalrus** [comment] 2021-02-06 18:27
Are you sure you don't have any sort of stray/invalid characters in your code? This should work - can you send your actual code?

**Comment by zimzaza4** [comment] 2021-03-06 11:37
Oh

**Comment by zimzaza4** [comment] 2021-03-06 11:40
Code:
![IMG20210306193812](https://user-images.githubusercontent.com/53421735/110205574-bc665180-7eb3-11eb-8d2f-006c013b5d06.jpg)

**Comment by zimzaza4** [comment] 2021-03-06 11:40
![IMG20210306193827](https://user-images.githubusercontent.com/53421735/110205605-d9028980-7eb3-11eb-8a13-8e7f99f67681.jpg)

**Comment by zimzaza4** [comment] 2021-03-06 11:42
I used the examples in the wiki, but none of them work properly

**Comment by APickledWalrus** [comment] 2021-03-26 17:22
Sorry for the SUPER late reply. I had never got around to replying 😢 

I am still unable to reproduce this issue with your code:
```
on placeholderapi placeholder request for the prefix "custom":
	if the identifier is "message":
		set the result to "Hey there %player%!"
```

![image](https://user-images.githubusercontent.com/29044720/112669440-1a90af80-8e36-11eb-95b1-d0a1b944da3e.png)

Because I can't reproduce this, and I am not sure why you might be having this issue, I am going to have to close this issue. If anyone have any ideas, feel free to comment here.

**Closed by APickledWalrus** 2021-03-26 17:22 UTC
Labels: bug, waiting for response
